# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mcp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mcp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmcp.proto\x12\x03mcp\"J\n\x0e\x46\x65\x61tureRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x14\n\x0cpayload_type\x18\x02 \x01(\t\x12\x11\n\tsource_id\x18\x03 \x01(\t\"b\n\x0f\x46\x65\x61tureResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t2J\n\nMCPService\x12<\n\x0f\x45xtractFeatures\x12\x13.mcp.FeatureRequest\x1a\x14.mcp.FeatureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mcp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEATUREREQUEST']._serialized_start=18
  _globals['_FEATUREREQUEST']._serialized_end=92
  _globals['_FEATURERESPONSE']._serialized_start=94
  _globals['_FEATURERESPONSE']._serialized_end=192
  _globals['_MCPSERVICE']._serialized_start=194
  _globals['_MCPSERVICE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
